feat(docker): add MongoDB service with replica set configuration and update environment variables for development setup

diff --git a/server/Dockerfile b/server/Dockerfile
--- a/server/Dockerfile
+++ b/server/Dockerfile
@@ -1,13 +1,5 @@
 FROM node:lts-alpine AS base
 
-FROM base AS deps
-
-WORKDIR /app
-
-COPY package*.json ./
-
-RUN npm install --omit=dev
-
 FROM base AS build
 
 WORKDIR /app
@@ -20,26 +12,25 @@ COPY . .
 
 RUN npm run build
 
+# Verify Prisma Client was generated
+RUN test -d node_modules/.prisma/client || (echo "Prisma Client not found!" && exit 1)
+
 FROM base AS runner
 WORKDIR /app
 
 ENV NODE_ENV=production
+ENV PORT=3001
+ENV HOSTNAME="0.0.0.0"
 
 RUN addgroup --system --gid 1001 nodejs
 RUN adduser --system --uid 1001 api
 
-RUN chown api:nodejs .
-
-COPY --chown=api:nodejs --from=build /app/dist ./dist
-COPY --chown=api:nodejs --from=build /app/generated ./generated
 COPY --chown=api:nodejs package*.json ./
-COPY --from=deps /app/node_modules ./node_modules
+COPY --from=build /app/node_modules ./node_modules
+COPY --chown=api:nodejs --from=build /app/dist ./dist
 
 USER api
 
 EXPOSE 3001
-
-ENV PORT=3001
-ENV HOSTNAME="0.0.0.0"
 
 ENTRYPOINT ["npm", "run", "start"]
